version: '3.7'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: your_db_user
      DB_NAME: your_db_name
      DB_PASSWORD: your_db_password
      EMAIL_FROM: your_email@example.com
      EMAIL_PASSWORD: your_email_password
      SMTP_HOST: your_smtp_host
      SMTP_PORT: your_smtp_port

volumes:
  postgres_data:
